### ISSUE TITLE
Propagate -p 1 flag?

### ISSUE THREAD

**Issue by tleyden** [AlekSi/gocoverutil#4]
In the project I'm working on, we need to [set the -p 1](https://github.com/couchbase/sync_gateway/blob/master/test.sh#L15) flag to `go test`, for reasons mentioned in this [golang-nuts thread](https://groups.google.com/forum/#!topic/golang-nuts/yCidmjM9w6M).

I tried doing this with gocoverutil but got this error and help message:

```
gocoverutil -coverprofile=cover_sg_integration.out test -v -p 1 -covermode=count github.com/couchbase/sync_gateway/...
flag provided but not defined: -p
gocoverutil test command runs go test -cover with correct flags and merges profiles.

Packages list is passed as arguments; they may contain `...` patterns.
The list is expanded, sorted and duplicates are removed.
`go test -coverpkg` flag is set automatically to include all packages.
If tests are failing, gocoverutil exits with a correct exit code.
```

Is there currently a way to do this?  Would you accept a PR for it?

**Comment by AlekSi** [comment]
`gocoverutil test` always acts as if `-p 1` is passed. Now that flag is accepted and ignored.
Thank you for using this tool.

**Comment by tleyden** [comment]
@AlekSi is that true for https://github.com/AlekSi/gocoverutil/tree/5af34428fdab098825ea920c0d04d00c51460258?  We're on a slightly older build, due to using go 1.7 (which will change soon).

**Comment by tleyden** [comment]
Looks like it from looking at `func Test(..)`

```
       for _, p := range packages {
              ....
              cmd.Run()
       }
```

**Comment by AlekSi** [comment]
That's true that `go test` compiles test binaries and runs them in parallels for all passed arguments (packages). But `gocoverutil test` invokes `go test` several times, each time passing only a single package.
